import { ENERGY_COST_TO_GRAZE } from "../../../../common/config/constants";
import { DinosaurEvent } from "../../models/dinosaur-event.interface";

export const grazeEvents: DinosaurEvent[] = [
  {
    name: 'Bonne cueillette',
    description: 'Le dinosaure trouve une grande quantité de plantes.',
    minLevel: 0,
    experienceChange: 250,
    energyChange: -ENERGY_COST_TO_GRAZE,
    foodChange: 3000,
    hungerChange: -100,
    karmaChange: 0,
    weight: 5,
  },
  {
    name: 'Cueille légère',
    description: 'Le dinosaure ne trouve que quelques herbes.',
    minLevel: 0,
    experienceChange: 100,
    energyChange: -ENERGY_COST_TO_GRAZE,
    foodChange: 2500,
    hungerChange: -50,
    karmaChange: 0,
    weight: 3,
  },
  {
    name: 'Cueille légère mais épuisante',
    description: 'Le dinosaure ne trouve que quelques herbes, mais il s\'épuisé dans la montagne.',
    minLevel: 0,
    experienceChange: 100,
    energyChange: -ENERGY_COST_TO_GRAZE * 2,
    foodChange: 2500,
    hungerChange: -50,
    karmaChange: 0,
    weight: 3,
  },
  {
    name: 'Cueille inefficace',
    description: 'La cueillette est infructueuse, très peu de nourriture trouvée.',
    minLevel: 0,
    experienceChange: 250,
    energyChange: -ENERGY_COST_TO_GRAZE,
    foodChange: 2000,
    hungerChange: 0,
    karmaChange: 0,
    weight: 2,
  },
  {
    name: 'Pure galère',
    description: 'Ya R a se mettre sous la dent.',
    minLevel: 0,
    experienceChange: 500,
    energyChange: -ENERGY_COST_TO_GRAZE * 2,
    foodChange: 0,
    hungerChange: 0,
    karmaChange: 0,
    weight: 2,
  },
  {
    name: 'Cueillette avancée',
    description: 'Le dinosaure paît dans une région riche en ressources.',
    minLevel: 2,
    experienceChange: 300,
    energyChange: -ENERGY_COST_TO_GRAZE,
    foodChange: 4000,
    hungerChange: -150,
    karmaChange: 0,
    weight: 4,
  },
  {
    name: 'Cueillette experte',
    description: 'Le dinosaure paît efficacement, maximisant la nourriture récupérée.',
    minLevel: 3,
    experienceChange: 350,
    energyChange: -ENERGY_COST_TO_GRAZE,
    foodChange: 5000,
    hungerChange: -200,
    karmaChange: 0,
    weight: 3,
  },
  {
    name: 'Cueillette héroïque',
    description: 'Le dinosaure paît dans des conditions extrêmes, obtenant une grande quantité de nourriture.',
    minLevel: 4,
    experienceChange: 400,
    energyChange: -ENERGY_COST_TO_GRAZE,
    foodChange: 8000,
    hungerChange: -250,
    karmaChange: 0,
    weight: 2,
  },
  {
    name: 'Cueillette légendaire',
    description: 'Le dinosaure paît dans une région mythique, trouvant des plantes rares.',
    minLevel: 5,
    experienceChange: 500,
    energyChange: -ENERGY_COST_TO_GRAZE,
    foodChange: 10000,
    hungerChange: -300,
    karmaChange: 0,
    weight: 1,
  },
  {
    name: 'Cueillette suprême',
    description: 'Le dinosaure paît avec une maîtrise parfaite, obtenant une abondance de nourriture.',
    minLevel: 6,
    experienceChange: 600,
    energyChange: -ENERGY_COST_TO_GRAZE,
    foodChange: 12000,
    hungerChange: -350,
    karmaChange: 0,
    weight: 1,
  },
  {
    name: 'Cueillette épique',
    description: 'Le dinosaure paît dans une zone inexplorée, obtenant des ressources inestimables.',
    minLevel: 7,
    experienceChange: 750,
    energyChange: -ENERGY_COST_TO_GRAZE,
    foodChange: 15000,
    hungerChange: -400,
    karmaChange: 0,
    weight: 1,
  },
  {
    name: 'Cueillette cosmique',
    description: 'Le dinosaure paît dans une dimension parallèle, récoltant des plantes extraterrestres.',
    minLevel: 8,
    experienceChange: 1000,
    energyChange: -ENERGY_COST_TO_GRAZE * 4,
    foodChange: 20000,
    hungerChange: -500,
    karmaChange: 80,
    weight: 1,
  },
];
