import { ENERGY_COST_TO_HUNT } from "../../../../common/config/constants";
import { DinosaurEvent } from "../../models/dinosaur-event.interface";

export const huntEvents: DinosaurEvent[] = [
  {
    name: 'Chasse réussie',
    description: 'Le dinosaure attrape une grande proie, régénérant beaucoup de nourriture.',
    minLevel: 0,
    experienceChange: 250,
    energyChange: -ENERGY_COST_TO_HUNT,
    foodChange: 3000,
    hungerChange: 0,
    karmaChange: 0,
    weight: 1,
  },
  {
    name: 'Chasse modérée',
    description: 'Le dinosaure attrape une proie moyenne.',
    minLevel: 0,
    experienceChange: 100,
    energyChange: -ENERGY_COST_TO_HUNT,
    foodChange: 2500,
    hungerChange: 0,
    karmaChange: 0,
    weight: 3,
  },
  {
    name: 'Chasse modérée, mais épuisante',
    description: 'Le dinosaure galère pour attraper une proie moyenne.',
    minLevel: 0,
    experienceChange: 100,
    energyChange: -ENERGY_COST_TO_HUNT * 2,
    foodChange: 1500,
    hungerChange: 0,
    karmaChange: 0,
    weight: 3,
  },
  {
    name: 'Chasse difficile',
    description: 'La proie est petite et difficile à attraper.',
    minLevel: 0,
    experienceChange: 250,
    energyChange: -ENERGY_COST_TO_HUNT,
    foodChange: 1000,
    hungerChange: 0,
    karmaChange: 0,
    weight: 2,
  },
  {
    name: 'Chasse infructueuse',
    description: 'Le dinosaure n’a pas réussi à attraper de proie.',
    minLevel: 0,
    experienceChange: 250,
    energyChange: -ENERGY_COST_TO_HUNT,
    foodChange: 0,
    hungerChange: 0,
    karmaChange: 0,
    weight: 1,
  },
  {
    name: 'Chasse stratégique',
    description: 'Le dinosaure utilise des techniques de chasse avancées.',
    minLevel: 2,
    experienceChange: 300,
    energyChange: -ENERGY_COST_TO_HUNT,
    foodChange: 3500,
    hungerChange: 0,
    karmaChange: 0,
    weight: 2,
  },
  {
    name: 'Chasse féroce',
    description: 'Le dinosaure engage une chasse féroce, obtenant une proie exceptionnelle.',
    minLevel: 4,
    experienceChange: 400,
    energyChange: -ENERGY_COST_TO_HUNT,
    foodChange: 4000,
    hungerChange: 0,
    karmaChange: 0,
    weight: 2,
  },
  {
    name: 'Chasse légendaire',
    description: 'Le dinosaure réalise une chasse épique, capturant une proie mythique.',
    minLevel: 6,
    experienceChange: 600,
    energyChange: -ENERGY_COST_TO_HUNT,
    foodChange: 6000,
    hungerChange: 0,
    karmaChange: 0,
    weight: 1,
  },
  {
    name: 'Chasse nocturne',
    description: 'Le dinosaure chasse sous la lune, obtenant des ressources rares en se fatiguant moins.',
    minLevel: 8,
    experienceChange: 800,
    energyChange: -ENERGY_COST_TO_HUNT / 2,
    foodChange: 8000,
    hungerChange: 0,
    karmaChange: 0,
    weight: 1,
  },
];
