import { ENERGY_COST_TO_PRAY } from "../../../../common/config/constants";
import { DinosaurEvent } from "../../models/dinosaur-event.interface";

export const prayEvents: DinosaurEvent[] = [
  {
    name: 'Prière réussie',
    description: 'Le dinosaure réfléchit à ses erreurs passées.',
    minLevel: 5,
    experienceChange: 0,
    energyChange: -ENERGY_COST_TO_PRAY,
    foodChange: 0,
    hungerChange: 0,
    karmaChange: 500,
    weight: 100,
  },
  {
    name: 'Prière réussie',
    description: 'Le dinosaure à eu une illumination.',
    minLevel: 5,
    experienceChange: 500,
    energyChange: -ENERGY_COST_TO_PRAY,
    foodChange: 0,
    hungerChange: 0,
    karmaChange: 1500,
    weight: 20,
  },
  {
    name: 'Impossible de prier',
    description: 'Le dinosaure n avait pas la tête à cela.',
    minLevel: 5,
    experienceChange: 0,
    energyChange: -ENERGY_COST_TO_PRAY,
    foodChange: 0,
    hungerChange: 0,
    karmaChange: 0,
    weight: 30,
  },
  {
    name: 'Impossible de prier',
    description: 'Le dinosaure n était pas assez concentré.',
    minLevel: 5,
    experienceChange: 0,
    energyChange: -ENERGY_COST_TO_PRAY,
    foodChange: 0,
    hungerChange: 0,
    karmaChange: 0,
    weight: 20,
  },
  {
    name: 'prière exceptionnelle',
    description: 'Le dinosaure à rencontré une divinité.',
    minLevel: 5,
    experienceChange: 1000,
    energyChange: -ENERGY_COST_TO_PRAY,
    foodChange: 0,
    hungerChange: 0,
    karmaChange: 2500,
    weight: 5,
  },
];
