import { DinosaurEvent } from "../../models/dinosaur-event.interface";

export const wakeUpEvents: DinosaurEvent[] = [
  {
    name: 'Réveil en pleine forme',
    description: 'Le dinosaure se réveille prêt à tout retourner dans la jungle.',
    minLevel: 0,
    experienceChange: 0,
    energyChange: 0,
    foodChange: 0,
    hungerChange: 0,
    karmaChange: 0,
    weight: 2,
  },
  {
    name: 'Réveil malade',
    description: 'Le dinosaure se réveille malade, il manque d\'énergie.',
    minLevel: 0,
    experienceChange: 0,
    energyChange: -500,
    foodChange: 0,
    hungerChange: 0,
    karmaChange: 0,
    weight: 1,
  },
  {
    name: 'Réveil normal',
    description: 'Le dinosaure se réveille prêt pour une nouvelle journée.',
    minLevel: 0,
    experienceChange: 0,
    energyChange: -100,
    foodChange: 0,
    hungerChange: 0,
    karmaChange: 0,
    weight: 5,
  },
  {
    name: 'Réveil grognon',
    description: 'Le dinosaure se réveille de mauvaise humeur, grognant à tout va.',
    minLevel: 2,
    experienceChange: 0,
    energyChange: -200,
    foodChange: 0,
    hungerChange: 0,
    karmaChange: -50,
    weight: 2,
  },
  {
    name: 'Réveil affamé',
    description: 'Le dinosaure se réveille avec une faim de loup, prêt à dévorer tout ce qui bouge.',
    minLevel: 3,
    experienceChange: 0,
    energyChange: -100,
    foodChange: -500,
    hungerChange: 500,
    karmaChange: 0,
    weight: 4,
  },
  {
    name: 'Réveil explorateur',
    description: 'Le dinosaure se réveille avec une envie irrésistible d\'explorer de nouveaux territoires.',
    minLevel: 4,
    experienceChange: 500,
    energyChange: 0,
    foodChange: 0,
    hungerChange: 0,
    karmaChange: 0,
    weight: 2,
  },
  {
    name: 'Sommeil méditatif',
    description: 'Le dinosaure médite pendant son sommeil, regagnant un peu de karma.',
    minLevel: 5,
    experienceChange: 200,
    energyChange: 100,
    foodChange: 0,
    hungerChange: 0,
    karmaChange: 100,
    weight: 2,
  },
];