module.exports = {
    // Taux de déclin des caractéristiques par seconde
    BASE_FOOD: 10000,
    BASE_ENERGY: 10000,
    FOOD_DECAY_RATE_PER_SECOND: 5, 
    ENERGY_COST_TO_EAT: 1000,
    ENERGY_DECAY_RATE_PER_SECOND: 5, 
    ENERGY_RECOVERY_RATE_PER_SECOND: 10,
    MIN_FOOD_PER_MEAL: 500,
    MAX_FOOD_PER_MEAL: 1000,
    MAX_ENERGY_NO_SLEEP: 2500,
    MIN_ENERGY_TO_WAKE_UP: 7500
};
